# Generated by Django 5.2.15 on 2026-06-11 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم المجال (عربي)')),
                ('name_en', models.CharField(max_length=200, verbose_name='اسم المجال (إنجليزي)')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم المسار (عربي)')),
                ('name_en', models.CharField(max_length=200, verbose_name='اسم المسار (إنجليزي)')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.field', verbose_name='المجال')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, verbose_name='اسم المدرسة')),
                ('contact_person', models.CharField(max_length=255, verbose_name='ضابط الارتباط')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('project_title', models.CharField(max_length=500, verbose_name='عنوان المشروع/البحث')),
                ('document', models.FileField(upload_to='submissions/', verbose_name='ملف البحث (PDF)')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('reviewed', 'تمت المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقدم')),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='award.field', verbose_name='المجال')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='award.track', verbose_name='المسار')),
            ],
        ),
    ]
