# Generated by Django 5.2.15 on 2026-06-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='site_media/', verbose_name='خلفية الصفحة الرئيسية (صورة)')),
                ('hero_video', models.FileField(blank=True, help_text='إذا تم رفع فيديو، سيتم تجاهل الصورة وعرض الفيديو', null=True, upload_to='site_media/', verbose_name='خلفية الصفحة الرئيسية (فيديو)')),
            ],
            options={
                'verbose_name': 'إعداد الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.AddField(
            model_name='track',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='شرح المسار (عربي)'),
        ),
        migrations.AddField(
            model_name='track',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='شرح المسار (إنجليزي)'),
        ),
    ]
