# Generated by Django 5.2.15 on 2026-06-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_sitesetting_track_description_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'صورة'), ('video', 'فيديو')], default='image', max_length=10, verbose_name='نوع الملف')),
                ('media_file', models.FileField(upload_to='hero_slideshow/', verbose_name='الملف (صورة أو فيديو)')),
                ('order', models.IntegerField(default=0, verbose_name='ترتيب العرض (الأقل يظهر أولاً)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل؟')),
            ],
            options={
                'verbose_name': 'شريحة العرض',
                'verbose_name_plural': 'شرائح العرض الرئيسية (Slideshow)',
                'ordering': ['order'],
            },
        ),
    ]
