# Generated by Django 5.2.15 on 2026-06-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0003_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم عضو اللجنة')),
                ('title', models.CharField(max_length=200, verbose_name='الصفة/المنصب')),
                ('image', models.ImageField(upload_to='judges/', verbose_name='الصورة الشخصية')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'عضو تحكيم',
                'verbose_name_plural': 'لجنة التحكيم',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_text', models.CharField(max_length=100, verbose_name='التاريخ (مثال: 17 سبتمبر 2025)')),
                ('title', models.CharField(max_length=200, verbose_name='الحدث')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='مميز؟ (لحفل الختام)')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'حدث زمني',
                'verbose_name_plural': 'الجدول الزمني',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['order'], 'verbose_name': 'شريحة العرض', 'verbose_name_plural': 'شرائح العرض الرئيسية'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='موعد إغلاق التسجيل (للعداد التنازلي)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='site_media/', verbose_name='خلفية الصفحة الرئيسية (فيديو)'),
        ),
    ]
