# Generated by Django 5.2.15 on 2026-06-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0004_judge_timelineevent_alter_heroslide_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='جائزة انتصار عباس جردانة', max_length=200, verbose_name='العنوان الرئيسي الكبير')),
                ('hero_subtitle', models.CharField(default='للثقافة والتعليم', max_length=200, verbose_name='العنوان الفرعي')),
                ('about_text', models.TextField(default='تخليداً لذكرى السيدة انتصار عباس جردانة، أُطلقت هذه الجائزة لتكريم المبادرات التطوعية...', verbose_name='نص عن الجائزة')),
                ('vision_text', models.TextField(default='مجتمع نابض بالشغف والعطاء، يحتضن المبادرات.', verbose_name='نص الرؤية')),
                ('mission_text', models.TextField(default='تكريم القدرات التطوعية ودعم المبادرات كفعل نهضوي.', verbose_name='نص الرسالة')),
                ('principle_1', models.CharField(default='العطاء', max_length=100, verbose_name='المبدأ الأول')),
                ('principle_2', models.CharField(default='الريادة والابتكار', max_length=100, verbose_name='المبدأ الثاني')),
                ('principle_3', models.CharField(default='الاستدامة', max_length=100, verbose_name='المبدأ الثالث')),
                ('principle_4', models.CharField(default='الأثر والتأثر', max_length=100, verbose_name='المبدأ الرابع')),
                ('condition_1', models.CharField(default='نطاق العمل داخل المملكة الأردنية الهاشمية.', max_length=255, verbose_name='الشرط الأول')),
                ('condition_2', models.CharField(default='مراعاة المبادئ العامة ومجالات الجائزة.', max_length=255, verbose_name='الشرط الثاني')),
                ('condition_3', models.CharField(default='الالتزام بالميثاق الأخلاقي للعمل التطوعي.', max_length=255, verbose_name='الشرط الثالث')),
                ('condition_4', models.CharField(default='الفئة المستهدفة: طلبة التاسع - الثاني عشر.', max_length=255, verbose_name='الشرط الرابع')),
                ('condition_5', models.CharField(default='تقديم البحث بصيغة PDF (15-20 صفحة).', max_length=255, verbose_name='الشرط الخامس')),
                ('step_1', models.CharField(default='الاطلاع على دليل الجائزة ومعايير التحكيم.', max_length=255, verbose_name='الخطوة الأولى')),
                ('step_2', models.CharField(default='حضور اللقاء التعريفي بالمدرسة.', max_length=255, verbose_name='الخطوة الثانية')),
                ('step_3', models.CharField(default='تعبئة طلب الترشح الإلكتروني.', max_length=255, verbose_name='الخطوة الثالثة')),
                ('step_4', models.CharField(default='تقديم البحث والصور والفيديوهات.', max_length=255, verbose_name='الخطوة الرابعة')),
                ('step_5', models.CharField(default='تحديد ضابط ارتباط للمتابعة والتحكيم.', max_length=255, verbose_name='الخطوة الخامسة')),
                ('prize_1_desc', models.CharField(default='1500 دينار + درع العمل التطوعي المتميز', max_length=200, verbose_name='وصف الجائزة الأولى')),
                ('prize_2_desc', models.CharField(default='1000 دينار + درع الاستدامة والتأثير', max_length=200, verbose_name='وصف الجائزة الثانية')),
                ('prize_3_desc', models.CharField(default='500 دينار + درع أفضل فكرة ريادية', max_length=200, verbose_name='وصف الجائزة الثالثة')),
            ],
            options={
                'verbose_name': 'تحرير محتوى الصفحة الرئيسية (A to Z)',
                'verbose_name_plural': 'تحرير محتوى الصفحة الرئيسية (A to Z)',
            },
        ),
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0a1632', max_length=7, verbose_name='اللون الأساسي (الأزرق الداكن)')),
                ('secondary_color', models.CharField(default='#122450', max_length=7, verbose_name='اللون الثانوي')),
                ('gold_color', models.CharField(default='#c5a059', max_length=7, verbose_name='اللون الذهبي')),
                ('font_size', models.CharField(default='16px', max_length=4, verbose_name='حجم الخط الأساسي (مثال: 16px أو 18px)')),
            ],
            options={
                'verbose_name': 'إعدادات الألوان والتصميم',
                'verbose_name_plural': 'إعدادات الألوان والتصميم',
            },
        ),
    ]
