# Generated by Django 5.2.15 on 2026-06-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0005_homecontent_themesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(default='مبادرة تهدف لتكريم العطاء التطوعي للشباب اليافع في الأردن، تخليداً لمسيرة السيدة انتصار عباس جردانة.', verbose_name='نص عن الجائزة في الفوتر')),
                ('email', models.CharField(default='info@iaj-award.jo', max_length=100, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(default='+962 7X XXX XXXX', max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.CharField(default='المملكة الأردنية الهاشمية', max_length=200, verbose_name='العنوان')),
                ('copyright_text', models.CharField(default='جميع الحقوق محفوظة 2025 جائزة انتصار عباس جردانة للثقافة والتعليم', max_length=200, verbose_name='نص حقوق النشر')),
            ],
            options={
                'verbose_name': 'تحرير محتوى الفوتر (أسفل الصفحة)',
                'verbose_name_plural': 'تحرير محتوى الفوتر (أسفل الصفحة)',
            },
        ),
    ]
