# Generated by Django 5.2.15 on 2026-06-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0006_footercontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='تم إرسال طلبك بنجاح!', max_length=200, verbose_name='العنوان الرئيسي')),
                ('sub_text', models.TextField(default='شكراً لمشاركتكم في جائزة انتصار عباس جردانة. سيتم مراجعة الطلب.', verbose_name='النص الفرعي')),
                ('btn_text', models.CharField(default='العودة للرئيسية', max_length=100, verbose_name='نص زر العودة')),
            ],
            options={
                'verbose_name': 'تحرير صفحة النجاح (بعد التسجيل)',
                'verbose_name_plural': 'تحرير صفحة النجاح (بعد التسجيل)',
            },
        ),
        migrations.AddField(
            model_name='homecontent',
            name='btn_hero',
            field=models.CharField(default='تقدم لمشروعك الآن', max_length=100, verbose_name='زر الصفحة الرئيسية'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='btn_navbar',
            field=models.CharField(default='سجل الآن', max_length=100, verbose_name='زر النافبار العلوي'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='title_about',
            field=models.CharField(default='عن الجائزة', max_length=200, verbose_name='عنوان قسم عن الجائزة'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='title_apply',
            field=models.CharField(default='طلب التقديم للجائزة', max_length=200, verbose_name='عنوان قسم التقديم'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='title_fields',
            field=models.CharField(default='مجالات العمل التطوعي', max_length=200, verbose_name='عنوان قسم المجالات'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='title_judges',
            field=models.CharField(default='لجنة التحكيم', max_length=200, verbose_name='عنوان قسم لجنة التحكيم'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='title_prizes',
            field=models.CharField(default='قيمة الجوائز', max_length=200, verbose_name='عنوان قسم الجوائز'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='title_timeline',
            field=models.CharField(default='الإطار الزمني لمراحل الجائزة', max_length=200, verbose_name='عنوان قسم الجدول الزمني'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site_media/', verbose_name='شعار الموقع (Logo) - يظهر في الهيدر والفوتر'),
        ),
    ]
