# Generated by Django 5.2.15 on 2026-06-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0007_successpagecontent_homecontent_btn_hero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesetting',
            name='custom_css',
            field=models.TextField(blank=True, help_text='اكتب أو الصق أكواد CSS هنا لتغيير تصميم الموقع بدون لمس الكود الأساسي', null=True, verbose_name='CSS مخصص (لتغيير ألوان صفحات أو أحجام خطوط معينة)'),
        ),
    ]
