# Generated by Django 5.2.15 on 2026-06-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0008_themesetting_custom_css'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['order'], 'verbose_name': 'حدث زمني / خطوة', 'verbose_name_plural': 'الجدول الزمني ورحلة الترشح'},
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='وصف مختصر للخطوة'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='icon',
            field=models.CharField(blank=True, default='fa-check-circle', max_length=50, verbose_name='أيقونة FontAwesome (مثال: fa-bullhorn)'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='date_text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='التاريخ (مثال: 17 سبتمبر 2025) - اتركه فارغاً لو مش تاريخ'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='مميز؟ (مثل حفل الختام)'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان الخطوة/الحدث'),
        ),
    ]
