# Generated by Django 5.2.15 on 2026-06-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0009_alter_timelineevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='نبذة عن العضو'),
        ),
    ]
