# Generated by Django 5.2.15 on 2026-06-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0010_judge_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='modal_image',
            field=models.ImageField(blank=True, null=True, upload_to='timeline/', verbose_name='صورة البطاقة المنبثقة'),
        ),
    ]
