# Generated by Django 5.2.15 on 2026-06-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0011_timelineevent_modal_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد')),
                ('subject', models.CharField(max_length=300, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('media_type', models.CharField(choices=[('image', 'صورة'), ('video', 'فيديو')], default='image', max_length=10, verbose_name='النوع')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='الصورة')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='رابط يوتيوب')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='التصنيف')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'صورة/فيديو',
                'verbose_name_plural': 'معرض الصور',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='الصورة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور؟')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'الأخبار',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SectionBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(choices=[('home', 'الصفحة الرئيسية'), ('stats', 'الإحصائيات'), ('about', 'عن الجائزة'), ('fields', 'مجالات العمل التطوعي'), ('timeline', 'الجدول الزمني'), ('apply', 'طلب التقديم'), ('prizes', 'الجوائز'), ('judges', 'لجنة التحكيم'), ('footer', 'الفوتر')], max_length=20, unique=True, verbose_name='اختر القسم')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='صورة الخلفية')),
                ('enable_overlay', models.BooleanField(default=True, verbose_name='تفعيل الطبقة الشفافة؟')),
                ('overlay_color', models.CharField(default='#000000', max_length=7, verbose_name='لون الطبقة')),
                ('overlay_opacity', models.DecimalField(decimal_places=2, default=0.7, max_digits=3, verbose_name='نسبة الشفافية')),
                ('is_parallax', models.BooleanField(default=True, verbose_name='تفعيل الحركة (Parallax)؟')),
            ],
            options={
                'verbose_name': 'خلفية القسم',
                'verbose_name_plural': 'إدارة خلفيات الأقسام',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الجهة')),
                ('logo', models.ImageField(upload_to='sponsors/', verbose_name='شعار الجهة')),
                ('website', models.URLField(blank=True, null=True, verbose_name='رابط الموقع')),
                ('tier', models.CharField(choices=[('platinum', 'بلاتيني'), ('gold', 'ذهبي'), ('silver', 'فضي'), ('bronze', 'برونزي')], default='gold', max_length=20, verbose_name='مستوى الرعاية')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'شريك',
                'verbose_name_plural': 'الشركاء والرعاة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TickerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_html', models.TextField(verbose_name='النص (يدعم HTML)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل؟')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'رسالة شريط',
                'verbose_name_plural': 'رسائل الشريط الإخباري',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TickerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='تشغيل الشريط؟')),
                ('font_color', models.CharField(default='#c5a059', max_length=7, verbose_name='لون الخط')),
                ('bg_color', models.CharField(default='#0a1632', max_length=7, verbose_name='لون الخلفية')),
                ('bg_opacity', models.DecimalField(decimal_places=2, default=0.95, max_digits=3, verbose_name='شفافية الخلفية')),
                ('scroll_speed', models.IntegerField(default=30, verbose_name='السرعة')),
                ('fade_width', models.CharField(default='150px', max_length=5, verbose_name='مسافة التلاشي')),
            ],
            options={
                'verbose_name': 'إعدادات الشريط',
                'verbose_name_plural': 'إعدادات الشريط',
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='سنة الفوز')),
                ('school_name', models.CharField(max_length=255, verbose_name='اسم المدرسة')),
                ('project_title', models.CharField(max_length=500, verbose_name='عنوان المشروع')),
                ('rank', models.IntegerField(verbose_name='المركز')),
                ('image', models.ImageField(blank=True, null=True, upload_to='winners/', verbose_name='الصورة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='النبذة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'فائز',
                'verbose_name_plural': 'الفائزون',
                'ordering': ['-year', 'rank'],
            },
        ),
    ]
