# Generated by Django 5.2.15 on 2026-06-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0013_tickeritem_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionbackground',
            name='bg_color',
            field=models.CharField(blank=True, default='', help_text='اتركه فارغاً للاستخدام الافتراضي', max_length=7, verbose_name='لون الخلفية (مثال: #ffffff)'),
        ),
    ]
