# Generated by Django 5.2.15 on 2026-06-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0014_sectionbackground_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionbackground',
            name='bg_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='لون الخلفية (مثال: #ffffff)'),
        ),
    ]
