# Generated by Django 5.2.15 on 2026-06-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0015_alter_sectionbackground_bg_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideshowCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('image', 'صورة فقط'), ('video', 'فيديو (يوتيوب أو رفع ملف)'), ('text', 'نص فقط'), ('image_text', 'صورة + نص'), ('video_text', 'فيديو + نص')], default='image_text', max_length=12, verbose_name='نوع البطاقة')),
                ('image', models.ImageField(blank=True, help_text='مطلوبة لنوع (صورة) و(صورة+نص)', null=True, upload_to='slideshow/', verbose_name='الصورة')),
                ('video_url', models.URLField(blank=True, help_text='مثال: https://www.youtube.com/embed/VIDEO_ID', null=True, verbose_name='رابط فيديو (يوتيوب أو Vimeo)')),
                ('video_file', models.FileField(blank=True, help_text='بديل عن رابط يوتيوب — mp4/webm', null=True, upload_to='slideshow/videos/', verbose_name='ملف فيديو (رفع مباشر)')),
                ('heading', models.CharField(blank=True, default='', max_length=300, verbose_name='العنوان')),
                ('body_text', models.TextField(blank=True, default='', verbose_name='النص')),
                ('font_size', models.CharField(default='1rem', max_length=6, verbose_name='حجم الخط (مثال: 1rem أو 18px أو 1.2em)')),
                ('font_color', models.CharField(default='#ffffff', max_length=7, verbose_name='لون الخط')),
                ('font_weight', models.CharField(choices=[('300', 'خفيف (300)'), ('400', 'عادي (400)'), ('600', 'شبه سميك (600)'), ('700', 'سميك (Bold)'), ('900', 'أسود سميك (900)')], default='400', max_length=3, verbose_name='وزن الخط')),
                ('text_align', models.CharField(choices=[('center', 'وسط'), ('right', 'يمين'), ('left', 'يسار')], default='center', max_length=6, verbose_name='محاذاة النص')),
                ('card_bg_color', models.CharField(default='#000000', max_length=7, verbose_name='لون خلفية البطاقة')),
                ('card_opacity', models.DecimalField(decimal_places=2, default=0.45, max_digits=3, verbose_name='شفافية البطاقة (0.0 = شفافة تماماً، 1.0 = معتمة)')),
                ('border_radius', models.CharField(default='16px', max_length=6, verbose_name='استدارة الزوايا (مثال: 16px أو 0 أو 50%)')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة؟')),
            ],
            options={
                'verbose_name': 'بطاقة عرض شفافة',
                'verbose_name_plural': 'بطاقات العرض الشفافة (Slideshow)',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='sectionbackground',
            name='bg_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='لون خلفية بديل (بدون صورة)'),
        ),
    ]
