# Generated by Django 5.2.15 on 2026-06-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0016_slideshowcard_alter_sectionbackground_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshowcard',
            name='image',
            field=models.FileField(blank=True, help_text='مطلوبة لنوع (صورة) و(صورة+نص) — صور أو فيديو', null=True, upload_to='slideshow/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='slideshowcard',
            name='video_file',
            field=models.FileField(blank=True, help_text='بديل عن رابط يوتيوب — mp4/webm — ارفع فقط إذا ما عندك رابط', null=True, storage='videos', upload_to='slideshow/videos/', verbose_name='ملف فيديو (رفع مباشر)'),
        ),
    ]
