# Generated by Django 5.2.15 on 2026-06-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0017_alter_slideshowcard_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshowcard',
            name='image',
            field=models.FileField(blank=True, help_text='ارفع صورة (jpg/png/webp) أو فيديو (mp4/webm) — يقبل النوعين', null=True, upload_to='slideshow/', verbose_name='الصورة أو الفيديو (خلفية السلايد)'),
        ),
        migrations.AlterField(
            model_name='slideshowcard',
            name='video_file',
            field=models.FileField(blank=True, help_text='بديل عن رابط يوتيوب — mp4/webm — يُستخدم في بطاقة (فيديو+نص)', null=True, upload_to='slideshow/videos/', verbose_name='ملف فيديو إضافي (رفع مباشر)'),
        ),
    ]
