# Generated by Django 5.2.15 on 2026-06-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0018_alter_slideshowcard_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footercontent',
            options={'verbose_name': 'تحرير محتوى الفوتر', 'verbose_name_plural': 'تحرير محتوى الفوتر'},
        ),
        migrations.AlterModelOptions(
            name='homecontent',
            options={'verbose_name': 'تحرير محتوى الصفحة الرئيسية', 'verbose_name_plural': 'تحرير محتوى الصفحة الرئيسية'},
        ),
        migrations.AlterModelOptions(
            name='slideshowcard',
            options={'ordering': ['order'], 'verbose_name': 'بطاقة عرض شفافة', 'verbose_name_plural': 'بطاقات العرض الشفافة'},
        ),
        migrations.AlterModelOptions(
            name='successpagecontent',
            options={'verbose_name': 'تحرير صفحة النجاح', 'verbose_name_plural': 'تحرير صفحة النجاح'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='about_text',
            field=models.TextField(default='مبادرة تهدف لتكريم العطاء التطوعي...', verbose_name='نص عن الجائزة في الفوتر'),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='copyright_text',
            field=models.CharField(default='جميع الحقوق محفوظة 2025 جائزة انتصار عباس جردانة', max_length=200, verbose_name='نص حقوق النشر'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='about_text',
            field=models.TextField(default='تخليداً لذكرى السيدة انتصار عباس جردانة...', verbose_name='نص عن الجائزة'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='btn_navbar',
            field=models.CharField(default='سجل الآن', max_length=100, verbose_name='زر النافبار'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='hero_title',
            field=models.CharField(default='جائزة انتصار عباس جردانة', max_length=200, verbose_name='العنوان الرئيسي'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='mission_text',
            field=models.TextField(default='تكريم القدرات التطوعية...', verbose_name='نص الرسالة'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='vision_text',
            field=models.TextField(default='مجتمع نابض بالشغف والعطاء...', verbose_name='نص الرؤية'),
        ),
        migrations.AlterField(
            model_name='mediagallery',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mediagallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='mediagallery',
            name='media_type',
            field=models.CharField(choices=[('image', 'صورة'), ('video', 'فيديو')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='mediagallery',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediagallery',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mediagallery',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sectionbackground',
            name='bg_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='sectionbackground',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='sectionbackground',
            name='enable_overlay',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sectionbackground',
            name='is_parallax',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sectionbackground',
            name='overlay_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='sectionbackground',
            name='overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.7, max_digits=3),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='موعد إغلاق التسجيل'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site_media/', verbose_name='شعار الموقع'),
        ),
        migrations.AlterField(
            model_name='slideshowcard',
            name='border_radius',
            field=models.CharField(default='16px', max_length=6, verbose_name='استدارة الزوايا'),
        ),
        migrations.AlterField(
            model_name='slideshowcard',
            name='card_opacity',
            field=models.DecimalField(decimal_places=2, default=0.45, max_digits=3, verbose_name='شفافية البطاقة'),
        ),
        migrations.AlterField(
            model_name='slideshowcard',
            name='font_size',
            field=models.CharField(default='1rem', max_length=6, verbose_name='حجم الخط'),
        ),
        migrations.AlterField(
            model_name='slideshowcard',
            name='font_weight',
            field=models.CharField(choices=[('300', 'خفيف'), ('400', 'عادي'), ('600', 'شبه سميك'), ('700', 'سميك'), ('900', 'أسود سميك')], default='400', max_length=3, verbose_name='وزن الخط'),
        ),
        migrations.AlterField(
            model_name='slideshowcard',
            name='image',
            field=models.FileField(blank=True, help_text='ارفع صورة (jpg/png/webp) أو فيديو (mp4/webm)', null=True, upload_to='slideshow/', verbose_name='الصورة أو الفيديو'),
        ),
        migrations.AlterField(
            model_name='slideshowcard',
            name='video_file',
            field=models.FileField(blank=True, help_text='mp4/webm', null=True, upload_to='slideshow/videos/', verbose_name='ملف فيديو إضافي'),
        ),
        migrations.AlterField(
            model_name='slideshowcard',
            name='video_url',
            field=models.URLField(blank=True, help_text='مثال: https://www.youtube.com/embed/VIDEO_ID', null=True, verbose_name='رابط فيديو يوتيوب'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to='sponsors/'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='tier',
            field=models.CharField(choices=[('platinum', 'بلاتيني'), ('gold', 'ذهبي'), ('silver', 'فضي'), ('bronze', 'برونزي')], default='gold', max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='successpagecontent',
            name='sub_text',
            field=models.TextField(default='شكراً لمشاركتكم...', verbose_name='النص الفرعي'),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='custom_css',
            field=models.TextField(blank=True, null=True, verbose_name='CSS مخصص'),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='font_size',
            field=models.CharField(default='16px', max_length=4, verbose_name='حجم الخط'),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='primary_color',
            field=models.CharField(default='#0a1632', max_length=7, verbose_name='اللون الأساسي'),
        ),
        migrations.AlterField(
            model_name='tickeritem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tickeritem',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ticker/'),
        ),
        migrations.AlterField(
            model_name='tickeritem',
            name='message_html',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tickeritem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tickersetting',
            name='bg_color',
            field=models.CharField(default='#0a1632', max_length=7),
        ),
        migrations.AlterField(
            model_name='tickersetting',
            name='bg_opacity',
            field=models.DecimalField(decimal_places=2, default=0.95, max_digits=3),
        ),
        migrations.AlterField(
            model_name='tickersetting',
            name='fade_width',
            field=models.CharField(default='150px', max_length=5),
        ),
        migrations.AlterField(
            model_name='tickersetting',
            name='font_color',
            field=models.CharField(default='#c5a059', max_length=7),
        ),
        migrations.AlterField(
            model_name='tickersetting',
            name='scroll_speed',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='date_text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='icon',
            field=models.CharField(blank=True, default='fa-check-circle', max_length=50, verbose_name='أيقونة FontAwesome'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='مميز؟'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='winners/'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='winner',
            name='project_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='winner',
            name='rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='winner',
            name='school_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='winner',
            name='year',
            field=models.IntegerField(),
        ),
    ]
