# Generated by Django 5.2.15 on 2026-06-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0019_alter_footercontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='النص')),
                ('news_date', models.DateField(verbose_name='تاريخ الخبر')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'آخر الأخبار',
                'ordering': ['-news_date'],
            },
        ),
    ]
