# Generated by Django 5.2.15 on 2026-06-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0020_newsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='النص')),
                ('image', models.FileField(blank=True, upload_to='success_stories/', verbose_name='الصورة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قصة نجاح',
                'verbose_name_plural': 'قصص النجاح',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('youtube_url', models.URLField(verbose_name='رابط يوتيوب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فيديو',
                'verbose_name_plural': 'مكتبة الفيديو',
                'ordering': ['order'],
            },
        ),
    ]
