# Generated by Django 5.2.15 on 2026-06-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0021_successstory_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('image', models.FileField(upload_to='photos/', verbose_name='الصورة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'معرض الصور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WinnerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'فئة فوز',
                'verbose_name_plural': 'فئات الفوز',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='NewsItem',
        ),
        migrations.AddField(
            model_name='winner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعّل'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='project_title',
            field=models.CharField(max_length=500, verbose_name='عنوان المشروع'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='rank',
            field=models.IntegerField(verbose_name='المرتبة'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='school_name',
            field=models.CharField(max_length=255, verbose_name='اسم المدرسة'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='year',
            field=models.IntegerField(verbose_name='السنة'),
        ),
        migrations.AddField(
            model_name='winner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='award.winnercategory', verbose_name='الفئة'),
        ),
    ]
